-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 16:07:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pichincha
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pichincha` ;

-- -----------------------------------------------------
-- Schema pichincha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pichincha` DEFAULT CHARACTER SET latin1 ;
USE `pichincha` ;

-- -----------------------------------------------------
-- Table `pichincha`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pichincha`.`cliente` (
  `id_cliente` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `genero` VARCHAR(255) NULL DEFAULT NULL,
  `identificacion` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(255) NULL DEFAULT NULL,
  `contrasena_cliente` VARCHAR(255) NULL DEFAULT NULL,
  `estado_cliente` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pichincha`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pichincha`.`cuenta` (
  `id_cuenta` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `estado_cuenta` BIT(1) NULL DEFAULT NULL,
  `numero_cuenta` VARCHAR(255) NULL DEFAULT NULL,
  `saldo_inicial_cuenta` BIGINT(20) NULL DEFAULT NULL,
  `tipo_cuenta` VARCHAR(255) NULL DEFAULT NULL,
  `fk_cliente_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cuenta`),
  CONSTRAINT `FK8nwsq61xvyhcmeysme542nbsd`
    FOREIGN KEY (`fk_cliente_id`)
    REFERENCES `pichincha`.`cliente` (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK8nwsq61xvyhcmeysme542nbsd` ON `pichincha`.`cuenta` (`fk_cliente_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pichincha`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pichincha`.`movimiento` (
  `id_movimiento` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fecha_movimiento` DATETIME(6) NULL DEFAULT NULL,
  `saldo` DOUBLE NULL DEFAULT NULL,
  `tipo_movimiento` VARCHAR(255) NULL DEFAULT NULL,
  `valor_movimiento` DOUBLE NULL DEFAULT NULL,
  `fk_cuenta_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_movimiento`),
  CONSTRAINT `FKoesldewtlgocah1gpd3ve4dsb`
    FOREIGN KEY (`fk_cuenta_id`)
    REFERENCES `pichincha`.`cuenta` (`id_cuenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FKoesldewtlgocah1gpd3ve4dsb` ON `pichincha`.`movimiento` (`fk_cuenta_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
